version: '3'

services:
  # php
  export-excel_php:
    container_name: export-excel_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./laravel:/var/www/laravel
      #- ./.git:/var/www/.git

  # web
  export-excel_web:
    image: nginx
    container_name: export-excel_web
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/laravel
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - export-excel_php

  # db
  db:
    image: mariadb
    container_name: export-excel_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: export-excel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    ports:
    - 3306:3306

  # phpMyAdmin
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: export-excel_pma
    ports:
      - 8001:80
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      PMA_HOST: db